blank_issues_enabled: true
contact_links:
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
name: "Contribute Resources"
description: Add your tools name ,link & description here.
labels: ["tools"]
body:
  - type: markdown
    attributes:
      value: |
        Please check if your recommend tools exists or not, you can search on  [cliphive.tk](https://cliphive.tk).
  - type: input
    id: link
    attributes:
      label: Link / URL
      description: You must put up a link to your recommended resource or tool; if no link is provided, we may close it.
      placeholder: https://cliphive.tk
    validations:
      required: true
   - type: input
    id: link
    attributes:
      label: GitHub Source link / Any other alternative 
      description: You can provide canonical links /alternative domain link /Project Source link for the resoource if available
      placeholder: https://github.com/VidhyaVarshanyJS/ClipHive
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe about the site niche or its purpose.If no description is provided we might close it.
      placeholder: This Website lets you to ...
    validations:
      required: true
