name: Contribute Resources
description: Add your tools name ,link & description here.
body:
  - type: markdown
    attributes:
      value: |
         Please check if your recommend tools exists or not, you can search on  [cliphive.tk](https://cliphive.tk).
  - type: input
    id: link
    attributes:
      label: Link /URL
      description: You must put up a link to your recommended resource or tool; if no link is provided, we may close it.
      placeholder: https://cliphive.tk
    validations:
      required: true  
  - type: input
    id: aliaslink
    attributes:
      label: GitHub Source link / Any other alternative 
      description: You can provide canonical links /alternative domain link /Project Source link for the resoource if available
      placeholder: https://github.com/VidhyaVarshanyJS/ClipHive
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Which steps do we need to take to reproduce this error?

